import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [status, setStatus] = useState('not sent');

  const fetchScreenshots = async() => {
    const response = await fetch('/api/hello');
    const data = await response.json();

    setStatus( oldStatus => data.status);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://rankfuse.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <Image src="/rank-fuse-logo.png" alt="Vercel Logo" width={150} height={52} />
        </a>
      </footer>
    </div>
  )
}
